services:

  htpasswd-forward-auth:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v5
        - linux/arm/v6
        - linux/arm/v7
        - linux/ppc64le
        - linux/s390x
        - linux/riscv64
        - linux/386
        - windows/amd64
        - windows/386
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unspecified}
      x-bake:
        tags:
        - arulrajnet/htpasswd-forward-auth:dev
        - arulrajnet/htpasswd-forward-auth:${GIT_COMMIT:-dev}
        - arulrajnet/htpasswd-forward-auth:${CUSTOM_TAG_NAME:-dev}
    image: arulrajnet/htpasswd-forward-auth:dev
    command: /htpasswd-forward-auth
    environment:
      LOG_LEVEL: debug
